# Generated by Django 4.2.2 on 2023-06-16 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='AtividadeComplementar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('carga_horaria', models.CharField(max_length=30, verbose_name='Carga Horária')),
                ('instituicao', models.CharField(max_length=100, verbose_name='Instituição')),
                ('ano_conclusao', models.IntegerField(verbose_name='Ano de Conclusão')),
                ('arquivo', models.FileField(upload_to='', verbose_name='Arquivo')),
                ('observacao', models.TextField(max_length=500, verbose_name='Observação')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Alunos')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='core.tipoatividade', verbose_name='Atividade')),
            ],
        ),
    ]
